name: Update protobuf definitions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install protoc
      uses: arduino/setup-protoc@v3

    - name: Install dependencies
      run: npm install

    - name: Load protobuf definitions
      run: npm run load

    - name: Build protobuf definitions
      run: |
        npm run build
        npm run js
        npm run py

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update protobuf definitions
